language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_script:
  - echo $TRAVIS_PYTHON_VERSION;
  - echo [[ $TRAVIS_PYTHON_VERSION != 3.2 ]];
  - if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then pip install -r test_requirements.txt; fi
script:
  - "python -B -m unittest discover"
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then coveralls; fi