language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest --cov=optional
after_success:
  - poetry run coveralls
