language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest --cov=optional
after_success:
  - poetry run coveralls
