#!/usr/bin/env bash
#MISE description="Check for editorconfig violations using editorconfig-checker"

set -o nounset
set -o errexit
set -o pipefail

editorconfig () {
    editorconfig-checker
}

editorconfig
