name: typecheck
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "2.1.4"

      - name: Install Mise
        uses: jdx/mise-action@v3
        with:
          experimental: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install optional
        run: poetry install --all-extras

      - name: Run Type Checker
        run: just typecheck
